name: JoinSound
main: ghost\JoinSound\Main
author: ghost
api: 4.0.0
version: 1.0

commands:
  joinsound:
    description: information
    usage: "/joinsound"
    permission: joinsound.command.joinsound
permissions:
  joinsound.command.joinsound:
    description: "commande pour savoir qui a fais se plugin"
    default: true