name: JoinSound
main: ghost\JoinSound\Main
author: ghost
api: 4.0.0
version: 1.0

commands:
  joinsound:
    description: "information"
    permission: "join.sound"

permissions:
  join.sound:
    description: "information"
    default: op